-- CREATE TABLE IF NOT EXISTS Movies(
--    title    VARCHAR(41) NOT NULL PRIMARY KEY
--   ,year     INTEGER  NOT NULL
--   ,origin   VARCHAR(10) NOT NULL
--   ,genre    VARCHAR(58) NOT NULL
--   ,director VARCHAR(35) NOT NULL
--   ,poster   VARCHAR(41) NOT NULL
--   ,wikiLink VARCHAR(71) NOT NULL
--   ,cast     VARCHAR(238) NOT NULL
-- );

+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| Movie_ID   | int(11)     | NO   | PRI | NULL    | auto_increment |
| Movie_Name | varchar(50) | NO   |     | NULL    |                |
| Poster     | varchar(50) | YES  |     | NULL    |                |
| Director   | varchar(50) | YES  |     | NULL    |                |
| Cast       | varchar(50) | YES  |     | NULL    |                |
| Wiki_Link  | varchar(50) | YES  |     | NULL    |                |
| Genre      | varchar(58) | NO   |     | NULL    |                |
| Origin     | varchar(10) | NO   |     | NULL    |                |
| Year       | int(11)     | NO   |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+

ALTER TABLE Movie_Table ADD Rating INT;

ALTER TABLE Movie_Table
ADD Year INTEGER  NOT NULL;

	
TRUNCATE TABLE Movie_Table;


select * from Movie_Table;


INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Romeo Must Die',2000,'American','action','Andrzej Bartkowiak','Romeo Must Die','https://en.wikipedia.org/wiki/Romeo_Must_Die','Jet Li, Aaliyah, Delroy Lindo');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Baytown Outlaws',2013,'American','action','Barry Battles','The Baytown Outlaws','https://en.wikipedia.org/wiki/The_Baytown_Outlaws','Andre Braugher, Eva Longoria, Clayne Crawford, Daniel Cudmore, Travis Fimmel, Billy Bob Thornton');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Fast & Furious 6',2013,'American','action','Justin Lin','Fast & Furious 6','https://en.wikipedia.org/wiki/Fast_%26_Furious_6','Vin Diesel, Paul Walker, Dwayne Johnson, Michelle Rodriguez, Jordana Brewster, Tyrese Gibson, Chris Bridges, Sung Kang, Luke Evans, Gina Carano, John Ortiz, Gal Gadot, Joe Taslim, Clara Paget, Elsa Pataky, Kim Kold, Rita Ora, Shea Whigham');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Avengers: Age of Ultron',2015,'American','action','Joss Whedon','Avengers Age of Ultron','https://en.wikipedia.org/wiki/Avengers:_Age_of_Ultron','Robert Downey Jr, Chris Evans, Chris Hemsworth, Mark Ruffalo');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Kung Fu Man',2013,'Chinese','action','Ning Ying, Yuen Cheung-yan','Kung Fu Man','https://en.wikipedia.org/wiki/Kung_Fu_Man_(film)','Tiger Chen, Jiang Mengjie, Shen Lin, Arman Darbo, Yuen Cheung-yan, Vanessa Branch, Igor Darbo, Andre McCoy');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Gojoe',2000,'Japanese','action','Ishii, GakuryuGakuryu Ishii','Gojoe','https://en.wikipedia.org/wiki/Gojoe','Tadanobu Asano, Masatoshi Nagase');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Killer Punjabi',2016,'Punjabi','action','Lakhvir Bansi','Killer Punjabi','https://en.wikipedia.org/wiki/Killer_Punjabi','Gulshan Grover, Pooja Batra, Balinder Johal, Kailey Rav');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('A Dark Truth',2013,'American','action, thriller','Damian Lee','A Dark Truth','https://en.wikipedia.org/wiki/A_Dark_Truth','Andy GarcÃ­a, Kim Coates, Deborah Kara Unger, Kevin Durand, Lara Daans, Devon Bostick, Steven Bauer, Al Sapienza, Julio Mechoso, Eva Longoria, Forest Whitaker');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Olympus Has Fallen',2013,'American','action, thriller','Antoine Fuqua','Olympus Has Fallen','https://en.wikipedia.org/wiki/Olympus_Has_Fallen','Gerard Butler, Aaron Eckhart and Morgan Freeman, Angela Bassett, Robert Forster, Cole Hauser, Finley Jacobsen, Ashley Judd, Melissa Leo, Dylan McDermott, Radha Mitchell, Rick Yune');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Erin Brockovich',2000,'American','biography','Steven Soderbergh','Erin Brockovich','https://en.wikipedia.org/wiki/Erin_Brockovich_(film)','Julia Roberts, Albert Finney, Aaron Eckhart');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Ray',2004,'American','biography','Taylor Hackford','Ray','https://en.wikipedia.org/wiki/Ray_(film)','Jamie Foxx');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Pursuit of Happiness',2006,'American','biography','Gabriele Muccino','The Pursuit of Happiness','https://en.wikipedia.org/wiki/The_Pursuit_of_Happyness','Will Smith, Jaden Smith');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Mao''s Last Dancer',2009,'Australian','biography','Bruce Beresford','Mao''s Last Dancer','https://en.wikipedia.org/wiki/Mao%27s_Last_Dancer_(film)','Bruce Greenwood, Chi Cao, Kyle MacLachlan, Joan Chen');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('American Made',2017,'American','biography, action, comedy, crime, drama, history, thriller','Doug Liman','American Made','https://en.wikipedia.org/wiki/American_Made_(film)','Doug Liman (director); Gary Spinelli (screenplay); Tom Cruise, Domhnall Gleeson, Sarah Wright, Jayma Mays, Jesse Plemons');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Beautiful',2000,'American','comedy','Sally Field','Beautiful','https://en.wikipedia.org/wiki/Beautiful_(2000_film)','Minnie Driver, Hallie Kate Eisenberg, Kathleen Turner');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Little Nicky',2000,'American','comedy','Steven Brill','Little Nicky','https://en.wikipedia.org/wiki/Little_Nicky','Adam Sandler, Patricia Arquette, Harvey Keitel');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Seventeen Again',2000,'American','comedy','Jeffrey W. Byrd','Seventeen Again','https://en.wikipedia.org/wiki/Seventeen_Again','Tamera Mowry, Tia Mowry, Maia Campbell');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Animal',2001,'American','comedy','Luke Greenfield','The Animal','https://en.wikipedia.org/wiki/The_Animal','Rob Schneider, Colleen Haskell, John C. McGinley, Edward Asner');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Corky Romano',2001,'American','comedy','Rob Pritts','Corky Romano','https://en.wikipedia.org/wiki/Corky_Romano','Chris Kattan, Peter Falk, Fred Ward');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Death to Smoochy',2002,'American','comedy','Danny DeVito','Death to Smoochy','https://en.wikipedia.org/wiki/Death_to_Smoochy','Robin Williams, Edward Norton, Danny DeVito, Catherine Keener, Jon Stewart');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Camp Takota',2014,'American','comedy','Chris Riedell','Camp Takota','https://en.wikipedia.org/wiki/Camp_Takota','Grace Helbig, Hannah Hart, Mamrie Hart');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Wog Boy',2000,'Australian','comedy','Aleksi Vellis','The Wog Boy','https://en.wikipedia.org/wiki/The_Wog_Boy','Nick Giannopoulos, Vince Colosimo, Abi Tucker, Lucy Bell');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Hera Pheri',2000,'Bollywood','comedy','Priyadarshan','Hera Pheri','https://en.wikipedia.org/wiki/Hera_Pheri_(2000_film)','Akshay Kumar, Suniel Shetty, Tabu, Paresh Rawal');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Blow Dry',2001,'British','comedy','Paddy Breathnach','Blow Dry','https://en.wikipedia.org/wiki/Blow_Dry','Alan Rickman, Natasha Richardson');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('No Men Beyond This Point',2015,'Canadian','comedy','Mark Sawers','No Men Beyond This Point','https://en.wikipedia.org/wiki/No_Men_Beyond_This_Point','Patrick Gilmore, Kristine Cofsky, Rekha Sharma');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Goodbye Mr. Loser',2015,'Chinese','comedy','Yan Fei, Peng Damo','Goodbye Mr. Loser','https://en.wikipedia.org/wiki/Goodbye_Mr._Loser','Shen Teng, Ma Li, Yin Zheng, Ai Lun, Wang Zi, Tian Yu, Song Yang, Chang Yuan, Li Ping, Lee Li-chun, Zhang Yiming');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('A Farewell to Jinu',2015,'Japanese','comedy','Suzuki Matsuo','A Farewell to Jinu','https://en.wikipedia.org/wiki/A_Farewell_to_Jinu','Ryuhei Matsuda, Takako Matsu, Sadayo Abe');


INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Dady Cool Munde Fool',2013,'Punjabi','comedy','Simerjit Singh','Dady Cool Munde Fool','https://en.wikipedia.org/wiki/Dady_Cool_Munde_Fool','Amrinder Gill, Harish Verma, Jaswinder Bhalla, Yuvika Chaudhary, Ihana Dhillon, Amar Noorie, Upasana Singh, Rana Ranbir, Karamjit Anmol,');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Double Di Trouble',2014,'Punjabi','comedy','Smeep Kang','Double Di Trouble','https://en.wikipedia.org/wiki/Double_Di_Trouble','Dharmendra, Gippy Grewal, Poonam Dhillon, Rana Ranbir, Mannisha Lamba, Kulraj Randhawa, Gurpreet Ghuggi');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Poisons or the World History of Poisoning',2001,'Russian','comedy','Karen Shakhnazarov','Poisons or the World History of Poisoning','https://en.wikipedia.org/wiki/Poisons_or_the_World_History_of_Poisoning','Ignat Akrachkov, Oleg Basilashvili, Zhanna Dudanova, Aleksandr Bashirov');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Believer',2001,'American','drama','Henry Bean','The Believer','https://en.wikipedia.org/wiki/The_Believer_(film)','Ryan Gosling, Billy Zane, Theresa Russell');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Grey Zone',2001,'American','drama','Tim Blake Nelson','The Grey Zone','https://en.wikipedia.org/wiki/The_Grey_Zone','Harvey Keitel, Natasha Lyonne, David Arquette');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('K-PAX',2001,'American','drama','Iain Softley','K-PAX','https://en.wikipedia.org/wiki/K-PAX_(film)','Kevin Spacey, Jeff Bridges, Mary McCormack, Alfre Woodard');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Spy Game',2001,'American','drama','Tony Scott','Spy Game','https://en.wikipedia.org/wiki/Spy_Game','Robert Redford, Brad Pitt');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Florida Project',2017,'American','drama','Sean Baker','The Florida Project','https://en.wikipedia.org/wiki/The_Florida_Project','Sean Baker (director/screenplay); Chris Bergoch (screenplay); Willem Dafoe, Bria Vinaite, Brooklynn Prince, Valeria Cotto, Caleb Landry Jones');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Phantom Thread',2017,'American','drama','Paul Thomas Anderson','Phantom Thread','https://en.wikipedia.org/wiki/Phantom_Thread','Paul Thomas Anderson (director/screenplay); Daniel Day-Lewis, Lesley Manville, Richard Graham, Vicky Krieps');


select * from Movie_Table;

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Lion',2016,'Australian','drama','Garth Davis','Lion','https://en.wikipedia.org/wiki/Lion_(2016_film)','Rooney Mara, Nicole Kidman, Dev Patel, David Wenham');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Jolly LLB 2',2017,'Bollywood','drama','Subhash Kapoor','Jolly LLB 2','https://en.wikipedia.org/wiki/Jolly_LLB_2','Akshay Kumar, Huma Qureshi & Saurabh Shukla');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Two Lovers and a Bear',2016,'Canadian','drama','Kim Nguyen','Two Lovers and a Bear','https://en.wikipedia.org/wiki/Two_Lovers_and_a_Bear','Dane DeHaan, Tatiana Maslany, Gordon Pinsent');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Assassination Classroom: Graduation',2016,'Japanese','drama, action, sci-fi, comedy','Takeshi Furusawa','Assassination Classroom Graduation','https://en.wikipedia.org/wiki/Assassination_Classroom:_Graduation','Ryosuke Yamada, Kazunari Ninomiya, Masaki Suda, Seika Taketomi, Mio YÅ«ki, Miku Uehara');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Wall',2017,'American','drama, thriller','Doug Liman','The Wall','https://en.wikipedia.org/wiki/The_Wall_(2017_film)','Doug Liman (director); Dwain Worrell (screenplay); Aaron Taylor-Johnson, John Cena');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Inconceivable',2017,'American','drama, thriller','Jonathan Baker','Inconceivable','https://en.wikipedia.org/wiki/Inconceivable_(2017_film)','Jonathan Baker (director); Chloe King (screenplay); Nicolas Cage, Faye Dunaway, Gina Gershon, Natalie Eva Marie');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Beguiled',2017,'American','drama, western','Sofia Coppola (director','The Beguiled','https://en.wikipedia.org/wiki/The_Beguiled_(2017_film)','Sofia Coppola (director, screenplay); Colin Farrell, Nicole Kidman, Kirsten Dunst, Elle Fanning, Angourie Rice, Oona Laurence');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Blizzard',2003,'American','family','LeVar Burton','Blizzard','https://en.wikipedia.org/wiki/Blizzard_(film)','Brenda Blethyn, Christopher Plummer, Kevin Pollak');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Thunderstruck',2012,'American','family, sports, comedy','John Whitesell','Thunderstruck','https://en.wikipedia.org/wiki/Thunderstruck_(2012_film)','Kevin Durant, Taylor Gray, Brandon T. Jackson, Doc Shaw, Jim Belushi');


select * from Movie_Table;

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Barbie: The Princess and the Popstar',2012,'American','fantasy','Zeke Norton','Barbie: The Princess and the Popstar','https://en.wikipedia.org/wiki/Barbie:_The_Princess_and_the_Popstar','Kelly Sheridan, Ellie King, Jonathan Holmes, Allison Warnyca');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Clash of the Empires',2012,'American','fantasy','Joseph Lawson','Clash of the Empires','https://en.wikipedia.org/wiki/Clash_of_the_Empires','Christopher Judge, Bai Ling, Sun Korng, Kyle Morris');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Jack the Giant Killer',2013,'American','fantasy','Mark Atkins','Jack the Giant Killer','https://en.wikipedia.org/wiki/Jack_the_Giant_Killer_(2013_Asylum_film)','Ben Cross, Jane March, Jamie Atkins, Vicki Glover, Harry Dyer');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Jaani Dushman: Ek Anokhi Kahani',2002,'Bollywood','fantasy','Rajkumar Kohli','Jaani Dushman Ek Anokhi Kahani','https://en.wikipedia.org/wiki/Jaani_Dushman:_Ek_Anokhi_Kahani','Sunny Deol, Akshay Kumar, Sunil Shetty, Sonu Nigam, Arshad Warsi, Aftab Shivdasani, Manisha Koirala');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Rapture-Palooza',2013,'American','fantasy, comedy','Paul Middleditch','Rapture-Palooza','https://en.wikipedia.org/wiki/Rapture-Palooza','Craig Robinson, Anna Kendrick, John Francis Daley, Ken Jeong');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Prey',2009,'Australian','horror','George T. Miller','Prey','https://en.wikipedia.org/wiki/Prey_(2009_film)','Natalie Bassingthwaighte, Jesse Johnson, Natalie Walker, Ben Kermode');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Road Train',2010,'Australian','horror','Dean Francis','Road Train','https://en.wikipedia.org/wiki/Road_Train_(film)','Xavier Samuel, Bob Morley, Sophie Lowe, Georgina Haig');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Don''t Be Afraid of the Dark',2011,'Australian','horror','Matthew Robbins, Guillermo del Toro','Don''t Be Afraid of the Dark','https://en.wikipedia.org/wiki/Don%27t_Be_Afraid_of_the_Dark_(2011_film)','Guy Pearce, Katie Holmes, Bailee Madison');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Triangle',2009,'British','horror','Christopher Smith','Triangle','https://en.wikipedia.org/wiki/Triangle_(2009_British_film)','Melissa George, Liam Hemsworth, Rachael Carpani');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Ginger Snaps',2000,'Canadian','horror','John Fawcett','Ginger Snaps','https://en.wikipedia.org/wiki/Ginger_Snaps_(film)','Emily Perkins, Katharine Isabelle, Kris Lemche, Mimi Rogers, Danielle Hampton');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Altitude',2010,'Canadian','horror','Kaare Andrews','Altitude','https://en.wikipedia.org/wiki/Altitude_(film)','Mike Dopud, Jessica Lowndes, Julianna Guill');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Void',2016,'Canadian','horror','Steven Kostanski, Jeremy Gillespie','The Void','https://en.wikipedia.org/wiki/The_Void_(2016_film)','Ellen Wong, Aaron Poole, Evan Stern');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Backtrack',2016,'Australian','mystery, thriller','Michael Petroni','Backtrack','https://en.wikipedia.org/wiki/Backtrack_(2015_film)','Adrien Brody, Sam Neill, Robin McLeavy');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Enduring Love',2004,'British','romance','Roger Michell','Enduring Love','https://en.wikipedia.org/wiki/Enduring_Love_(film)','Daniel Craig, Rhys Ifans, Samantha Morton');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Yesterday Once More',2016,'Chinese','romance','Yoyo Yao','Yesterday Once More','https://en.wikipedia.org/wiki/Yesterday_Once_More_(2016_film)','Bai Jingting, Guo Shutong, Li Hongyi, Wang Herun, Ding Guansen, Zhao Wenlong');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Koizora',2007,'Japanese','romance','Aragaki Yui','Koizora','https://en.wikipedia.org/wiki/Koizora','[Haruma Miura]');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Badrinath Ki Dulhania',2017,'Bollywood','romance, comedy','Shashank Khaitan','Badrinath Ki Dulhania','https://en.wikipedia.org/wiki/Badrinath_Ki_Dulhania','Varun Dhawan & Alia Bhatt');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Miranda',2002,'British','romance, comedy','Marc Munden','Miranda','https://en.wikipedia.org/wiki/Miranda_(2002_film)','Christina Ricci, John Simm');
select * from Movie_Table;

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Namastey London',2007,'Bollywood','romance, comedy, drama, social','Vipul Amrutlal Shah','Namastey London','https://en.wikipedia.org/wiki/Namastey_London','Akshay Kumar, Katrina Kaif, Rishi Kapoor, Upen Patel, Ritesh Deshmukh, Javed Sheikh, Clive Standen, Nina Wadia');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Rockstar',2011,'Bollywood','romance, drama','Imtiaz Ali','Rockstar','https://en.wikipedia.org/wiki/Rockstar_(2011_film)','Ranbir Kapoor, Nargis Fakhri, Shammi Kapoor');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Raabta',2017,'Bollywood','romance, thriller','Dinesh Vijan','Raabta','https://en.wikipedia.org/wiki/Raabta_(film)','Sushant Singh Rajput, Kriti Sanon & Jim Sarbh');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Mehndi Waley Hath',2000,'Punjabi','romance, drama','Syed Noor','Mehndi Waley Hath','https://en.wikipedia.org/wiki/Mehndi_Waley_Hath','Saima, Moammar Rana, Babar Ali, Nirma');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Once Upon a Time',2017,'Chinese','romance, fantasy','Zhao Xiaoding Anthony LaMolinara','Once Upon a Time','https://en.wikipedia.org/wiki/Once_Upon_a_Time_(2017_film)','Liu Yifei, Yang Yang, Luo Jin');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Dil Jo Na Keh Saka',2017,'Bollywood','romantic, drama','Naresh Lalwani','Dil Jo Na Keh Saka','https://en.wikipedia.org/wiki/Dil_Jo_Na_Keh_Saka_(2017_Movie)','Himansh Kohli, Priya Banerjee');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Art of Woo',2001,'Canadian','romantic, comedy','Helen Lee','The Art of Woo','https://en.wikipedia.org/wiki/The_Art_of_Woo','Sook-Yin Lee, Adam Beach');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Jatt & Juliet',2012,'Punjabi','romantic, comedy','Anurag Singh','Jatt & Juliet','https://en.wikipedia.org/wiki/Jatt_%26_Juliet','Diljit Singh Dosanjh, Neeru Bajwa, Jaswinder Bhalla,BN Sharma, Rana Ranbir, Karamjeet Anmol, Sari Mercer, Upasana Singh');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Heer and Hero',2013,'Punjabi','romantic, comedy','Sagar S. Sharma','Heer and Hero','https://en.wikipedia.org/wiki/Heer_and_Hero','Manissha Lamba, Arya Babbar, Gurpreet Ghuggi, Hazel Keech, Preet Bhullar, Manoj Pahwa, Yograj Singh, Mukul Dev');
select * from Movie_Table;

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Mundeyan Ton Bachke Rahin',2014,'Punjabi','romantic, comedy','Navinder Kirpal Singh','Mundeyan Ton Bachke Rahin','https://en.wikipedia.org/wiki/Mundeyan_Ton_Bachke_Rahin','Roshan Prince, Jassi Gill, Simran Kaur Mundi, Sunny Gill, Bharti Singh, Anshu Sawhney, Minto, Hobby Dhaliwal, Sunita Dhir, Manoj Sabharwal');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Still Waters',2000,'Russian','romantic, comedy','Eldar Ryazanov','Still Waters','https://en.wikipedia.org/wiki/Still_Waters_(Russian_film)','Alexander Abdulov, Lyubov Polishchuk, Andrey Makarevich, Oksana Korostishevskaya, Olga Volkova');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Spring Subway',2002,'Chinese','romantic, drama','Zhang Yibai','Spring Subway','https://en.wikipedia.org/wiki/Spring_Subway','Xu Jinglei, Geng Le, Zhang Yang');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Nuan',2003,'Chinese','romantic, drama','Huo Jianqi','Nuan','https://en.wikipedia.org/wiki/Nuan','Guo Xiaodong, Li Jia');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Robot',2010,'Bollywood','sci-fi','S. Shankar','Robot','https://en.wikipedia.org/wiki/Enthiran','Rajinikanth, Aishwarya Rai, Danny Denzongpa');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Code 46',2003,'British','sci-fi','Michael Winterbottom','Code 46','https://en.wikipedia.org/wiki/Code_46','Tim Robbins, Samantha Morton');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Blame!',2017,'Japanese','sci-fi, action, spy','Hiroyuki Seshita','Blame!','https://en.wikipedia.org/wiki/Blame!_(film)','Kana Hanazawa, Takahiro Sakurai, Sora Amamiya, Mamoru Miyano, Aya Suzaki, Nobunaga Shimazaki');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Monsters',2010,'British','sci-fi, drama','Gareth Edwards','Monsters','https://en.wikipedia.org/wiki/Monsters_(2010_film)','Whitney Able, Scoot McNairy');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Chengdu, I Love You',2009,'Chinese','sci-fi, drama','Cui Jian, Fruit Chan','Chengdu, I Love You','https://en.wikipedia.org/wiki/Chengdu,_I_Love_You','Gao Yuanyuan');




INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Cube 2: Hypercube',2002,'Canadian','sci-fi, horror','Andrzej SekuÅ‚a','Cube 2 Hypercube','https://en.wikipedia.org/wiki/Cube_2:_Hypercube','Kari Matchett, Geraint Wyn Davies');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Tumhari Sulu',2017,'Bollywood','social, comedy','Ruchi Chaudhari','Tumhari Sulu','https://en.wikipedia.org/wiki/Tumhari_Sulu','Vidya Balan & Manav Kaul');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('A Shot at Glory',2000,'British','sport','Michael Corrente','A Shot at Glory','https://en.wikipedia.org/wiki/A_Shot_at_Glory','Robert Duvall, Michael Keaton');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('There''s Only One Jimmy Grimble',2000,'British','sports, drama','John Hay','There''s Only One Jimmy Grimble','https://en.wikipedia.org/wiki/There%27s_Only_One_Jimmy_Grimble','Lewis McKenzie, Gina McKee, Ray Winstone');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Shadowboxing 3: Last Round',2011,'Russian','sports, drama','Aleksei Sidorov','Shadowboxing 3 Last Round','https://en.wikipedia.org/wiki/Shadowboxing_3:_Last_Round','Denis Nikiforov, Yelena Panova, Andrey Panin, Pavel Derevyanko');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Quantum of Solace',2008,'British','spy, action','Marc Forster','Quantum of Solace','https://en.wikipedia.org/wiki/Quantum_of_Solace','Daniel Craig, Olga Kurylenko, Mathieu Amalric, Judi Dench');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Agent Vinod',2012,'Bollywood','suspense, thriller','Sriram Raghavan','Agent Vinod','https://en.wikipedia.org/wiki/Agent_Vinod_(2012_film)','Saif Ali Khan, Kareena Kapoor[20]');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Tag',2015,'Japanese','suspense, action, horror','Sion Sono','Tag','https://en.wikipedia.org/wiki/Tag_(2015_film)','Reina Triendl, Mariko Shinoda, Erina Mano');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Inside the Girls',2014,'Chinese','suspense, thriller','Liang Ting','Inside the Girls','https://en.wikipedia.org/wiki/Inside_the_Girls','Wen Xin, Cheng Yi, Zhao Duona, Andrew Yin, Jelly Zhao, Jing Gangshan, Wang Qianyi, Du Shuangyu');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Precipice Game',2016,'Chinese','suspense, thriller','Wang Zao','The Precipice Game','https://en.wikipedia.org/wiki/The_Precipice_Game','Ruby Lin, Peter Ho, Jin Shijia, Wang Ji, Gai Yuexi, Li Lin, Li Shangyi, Shi Zhi, Liu Shijie');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Restraint',2006,'Australian','thriller','David Deenan','Restraint','https://en.wikipedia.org/wiki/Ravenswood_(film)','Stephen Moyer, Travis Fimmel, Teresa Palmer');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Horseman',2008,'Australian','thriller','Steven Kastrissios','The Horseman','https://en.wikipedia.org/wiki/The_Horseman_(film)','Peter Marshall, Caroline Marohasy');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Last Dance',2012,'Australian','thriller','David Pulbrook','Last Dance','https://en.wikipedia.org/wiki/Last_Dance_(2012_film)','Firass Dirani, Julia Blake, Alan Hopgood');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Felony',2013,'Australian','thriller','Matthew Saville','Felony','https://en.wikipedia.org/wiki/Felony_(film)','Jai Courtney, Melissa George, Joel Edgerton, Tom Wilkinson');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Predestination',2014,'Australian','thriller','Spierig brothers','Predestination','https://en.wikipedia.org/wiki/Predestination_(film)','Ethan Hawke, Sarah Snook, Noah Taylor');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Cargo',2017,'Australian','thriller','Ben Howling, Yolanda Ramke','Cargo','https://en.wikipedia.org/wiki/Cargo_(2017_film)','Martin Freeman, Anthony Hayes, Caren Pistorius');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Kasoor',2001,'Bollywood','thriller','Vikram Bhatt','Kasoor','https://en.wikipedia.org/wiki/Kasoor','Lisa Ray, Aftab Shivdasani, Divya Dutta');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Anjaam',2007,'Bollywood','thriller','Anant Mahadevan','Anjaam','https://en.wikipedia.org/wiki/Anjaam','Emraan Hashmi, Tushar Kapoor');
select * from Movie_Table;


INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Murder 3',2013,'Bollywood','thriller','Vishesh Bhatt','Murder 3','https://en.wikipedia.org/wiki/Murder_3','Randeep Hooda, Aditi Rao Hydari, Mona Lizza');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Fourth Angel',2001,'British','thriller','John Irvin','The Fourth Angel','https://en.wikipedia.org/wiki/The_Fourth_Angel','Jeremy Irons, Forest Whitaker');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Baltic Storm',2003,'British','thriller','Reuben Leder','Baltic Storm','https://en.wikipedia.org/wiki/Baltic_Storm','Greta Scacchi, JÃ¼rgen Prochnow');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Knife Edge',2009,'British','thriller','Anthony Hickox','Knife Edge','https://en.wikipedia.org/wiki/Knife_Edge_(film)','Hugh Bonneville, Natalie Press');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Sidekick',2005,'Canadian','thriller','Blake Van de Graaf','Sidekick','https://en.wikipedia.org/wiki/Sidekick_(film)','David Ingram');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Chained',2012,'Canadian','thriller','Jennifer Lynch','Chained','https://en.wikipedia.org/wiki/Chained_(2012_film)','Vincent D''Onofrio, Julia Ormond');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Enemy',2013,'Canadian','thriller','Denis Villeneuve','Enemy','https://en.wikipedia.org/wiki/Enemy_(2013_film)','Jake Gyllenhall, Maclanie Laurent, Isabella Rossellini, Sarah Gadon');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Phantom of the Theatre',2016,'Chinese','thriller','Raymond Yip','Phantom of the Theatre','https://en.wikipedia.org/wiki/Phantom_of_the_Theatre','Ruby Lin, Tony Yang, Simon Yam, Huang Huan, Jing Gangshan, Lin Jiangguo, Natalie Meng, Zhang Zifeng, Huang Lei, Li Jing, He Yunwei');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Battle Royale',2000,'Japanese','thriller','Fukasaku, KinjiKinji Fukasaku','Battle Royale','https://en.wikipedia.org/wiki/Battle_Royale_(film)','Tatsuya Fujiwara');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Ghost',2008,'Russian','thriller','Karen Oganesyan','The Ghost','https://en.wikipedia.org/wiki/The_Ghost_(2008_film)','Konstantin Khabensky, Vladimir Mashkov, Chulpan Khamatova');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Anamika',2008,'Bollywood','thriller','Anant Mahadevan','Anamika','https://en.wikipedia.org/wiki/Anamika_(2008_film)','Dino Morea, Minissha Lamba, Koena Mitra, Aarti Chabria, Gulshan Grover');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Aankhen',2002,'Bollywood','thriller,  action','Vipul Shah','Aankhen','https://en.wikipedia.org/wiki/Aankhen_(2002_film)','Amitabh Bachchan, Akshay Kumar, Paresh Rawal, Arjun Rampal, Sushmita Sen, Kashmira Shah, Bipasha Basu');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Kites',2010,'Bollywood','thriller, romance','Anurag Basu','Kites','https://en.wikipedia.org/wiki/Kites_(film)','Hrithik Roshan, Kangana Ranaut, BÃ¡rbara Mori, Kabir Bedi, Nick Brown');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Kurbaan',2009,'Bollywood','thriller,  romance','Rensil DSilva','Kurbaan','https://en.wikipedia.org/wiki/Kurbaan_(2009_film)','Saif Ali Khan, Kareena Kapoor, Vivek Oberoi, Dia Mirza, Om Puri, Kirron Kher, Nauheed Cyrusi');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Ajnabee',2001,'Bollywood','thriller,  suspense,  crime','Abbas Mustan','Ajnabee','https://en.wikipedia.org/wiki/Ajnabee_(2001_film)','Bobby Deol, Akshay Kumar, Kareena Kapoor, Bipasha Basu');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Shikari',2000,'Bollywood','thriller, action, romance','N. Chandra','Shikari','https://en.wikipedia.org/wiki/Shikari_(2000_film)','Govinda, Karishma Kapoor, Tabu');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Dhoom 2',2006,'Bollywood','thriller, action, romance, musical','Sanjay Gadhvi','Dhoom 2','https://en.wikipedia.org/wiki/Dhoom_2','Hrithik Roshan, Abhishek Bachchan, Aishwarya Rai, Bipasha Basu, Uday Chopra, Rimi Sen');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Mom',2017,'Bollywood','thriller, drama','Ravi Udyawar','Mom','https://en.wikipedia.org/wiki/Mom_(film)','Sridevi, Akshaye Khanna & Nawazuddin Siddiqui');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Contract',2008,'Bollywood','thriller, spy','Ram Gopal Varma','Contract','https://en.wikipedia.org/wiki/Contract_(2008_film)','Adhvik Mahajan, Sakshi Gulati, Kishor Kadam, Sumeet Nijhawan');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Haunted Road',2014,'Chinese','thriller, horror','Tong Yijian','Haunted Road','https://en.wikipedia.org/wiki/Haunted_Road','Hong Soo-ah, Jiang Jo, Ni Musi, Peng Ling, Renata Tan, Gao Taiyu, Xu Yue');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Red Hill',2010,'Australian','thriller, western','Patrick Hughes','Red Hill','https://en.wikipedia.org/wiki/Red_Hill_(film)','Ryan Kwanten, Steve Bisley, Tom E. Lewis, Claire van der Boom');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Tomorrow, When the War Began',2010,'Australian','war','Stuart Beattie','Tomorrow, When the War Began','https://en.wikipedia.org/wiki/Tomorrow,_When_the_War_Began_(film)','Caitlin Stasey, Lincoln Lewis, Rachel Hurd-Wood, Chris Pang, Deniz Akdeniz, Andy Ryan, Phoebe Tonkin, Ashleigh Cummings');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Assembly',2007,'Chinese','war','Feng Xiaogang','Assembly','https://en.wikipedia.org/wiki/Assembly_(film)','Zhang Hanyu');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Cuckoo',2002,'Russian','war','Aleksandr Rogozhkin','Cuckoo','https://en.wikipedia.org/wiki/The_Cuckoo_(film)','Anni-Kristiina Juuso, Ville Haapasalo, Viktor Bychkov');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Dawns Here Are Quiet',2015,'Russian','war','Renat Davletyarov','The Dawns Here Are Quiet','https://en.wikipedia.org/wiki/The_Dawns_Here_Are_Quiet_(2015_film)','Pyotr Fyodorov, Anastasia Mikulchina, Evgenia Malakhova, Agniya Kuznetsova, Sofya Lebedeva, Kristina Asmus');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Battalion',2015,'Russian','war','Dmitriy Meshiev','Battalion','https://en.wikipedia.org/wiki/Battalion_(2015_film)','Maria Aronova, Maria Kozhevnikova, Valeriya Shkirando');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Lakshya',2004,'Bollywood','war, drama, action, romance','Farhan Akhtar','Lakshya','https://en.wikipedia.org/wiki/Lakshya_(film)','Hrithik Roshan, Preity Zinta, Sharad Kapoor, Amitabh Bachchan');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Joyeux Noel',2005,'British','war, drama','Christian Carion','Joyeux Noel','https://en.wikipedia.org/wiki/Joyeux_No%C3%ABl','Benno Furmann, Guillaume Canet, Gary Lewis');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Transit',2006,'Russian','war, drama','Aleksandr Rogozhkin','Transit','https://en.wikipedia.org/wiki/Transit_(2006_film)','Aleksei Serebryakov, Daniil Strakhov, Anastasiya Nemolyaeva');


INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Proposition',2005,'Australian','western','John Hillcoat','The Proposition','https://en.wikipedia.org/wiki/The_Proposition_(2005_film)','Guy Pearce, Stan Winston, Danny Huston');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Sweet Country',2017,'Australian','western','Warwick Thornton','Sweet Country','https://en.wikipedia.org/wiki/Sweet_Country_(2017_film)','Sam Neill, Bryan Brown, Thomas M. Wright, Matt Day');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('The Claim',2000,'British','western, romance','Michael Winterbottom','The Claim','https://en.wikipedia.org/wiki/The_Claim','Peter Mullan, Milla Jovovich');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Hero',2002,'Chinese','wuxia','Zhang Yimou','Hero','https://en.wikipedia.org/wiki/Hero_(2002_film)','Jet Li, Tony Leung, Maggie Cheung');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Flying Swords of Dragon Gate',2011,'Chinese','wuxia','Tsui Hark','Flying Swords of Dragon Gate','https://en.wikipedia.org/wiki/Flying_Swords_of_Dragon_Gate','Jet Li, Zhou Xun, Chen Kun, Li Yuchun, Gwei Lun-mei, Louis Fan, Mavis Fan');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Tracing Shadow',2009,'Chinese','wuxia, comedy','Francis Ng Marco Mak','Tracing Shadow','https://en.wikipedia.org/wiki/Tracing_Shadow','Francis Ng, Jaycee Chan');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Go Goa Gone',2013,'Bollywood','zombie, comedy','Raj Nidimoru, Krishna D.K.','Go Goa Gone','https://en.wikipedia.org/wiki/Go_Goa_Gone','Saif Ali Khan, Kunal Khemu, Vir Das, Puja Gupta[56]');

INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Fido',2006,'Canadian','zombie, comedy','Andrew Currie','Fido','https://en.wikipedia.org/wiki/Fido_(film)','Dylan Baker, Billy Connolly, Carrie-Anne Moss');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Survival of the Dead',2009,'Canadian','zombie, horror','George A. Romero','Survival of the Dead','https://en.wikipedia.org/wiki/Survival_of_the_Dead','Alan Van Sprang, Kenneth Welsh, Devon Bostick, Richard Fitzpatrick');
INSERT INTO Movie_Table(Movie_Name, Year, Origin, Genre, Director, Poster, Wiki_Link, Cast) VALUES ('Dead Rising: Watchtower',2015,'Canadian','zombie, horror','Zach Lipovsky','Dead Rising Watchtower','https://en.wikipedia.org/wiki/Dead_Rising:_Watchtower','Jesse Metcalfe, Dennis Haysbert, Virginia Madsen');

=========================================================================================================================================================================================================

